[package]
name = "aoc_2018"
version = "0.1.0"
authors = ["Ivaylo"]
edition = "2018"

[dependencies]
aoc-runner = "0.2.0"
aoc-runner-derive = "0.2.0"
regex = "1"
lazy_static = "1.2.0"
chrono = "0.4.6"
time = "0.1.41"
itertools = "0.8.0"